version: '3.1'
# https://www.docker.elastic.co/#

services:

  elasticsearch:
    # https://github.com/elastic/elasticsearch-docker
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
      - 9200:9200
    environment:
      - node.name=poder-elasticsearch-test
      - discovery.type=single-node
      # - "ELASTIC_PASSWORD=elastic"
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - esdata:/usr/share/elasticsearch/data

  kibana:
    # https://github.com/elastic/kibana-docker
    image: docker.elastic.co/kibana/kibana:6.4.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - ./config/kibana-plugins:/usr/share/kibana/plugins:ro
      - kbndata:/usr/share/kibana/data

  # configure-security:
  #   image: yauritux/busybox-curl
  #   command: security.sh
  #   environment:
  #     - "KIBANA_PASSWORD=kibana"
  #     - "LOGSTASH_PASSWORD=logstash"
  #   depends_on:
  #     - elasticsearch
  #   volumes:
  #     - ./config/security.sh:/bin/security.sh:ro

volumes:
  esdata:
    driver: local
  kbndata:
    driver: local
